site_name: IEEE Papers Mapper

theme:
  name: mkdocs
  color_mode: dark
  user_color_mode_toggle: true

repo_url: https://github.com/alex-anast/ieee-papers-mapper

nav:
  - Home: index.md
  - User Guide:
      - Overview: user_guide/overview.md
      - Installation: user_guide/installation.md
      - Usage: user_guide/usage.md
  - Developer Guide:
      - Code Structure: developer_guide/code_structure.md
      - API Reference: developer_guide/api_reference.md
  - About: about.md
